# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install --upgrade pip setuptools wheel"
  - "pip install --only-binary=pandas,numpy numpy pandas"

script:
  - "py.test tests.py"
